version: "2"
run:
  issues-exit-code: 2
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - godot
    - misspell
    - noctx
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    gocritic:
      disabled-checks:
        - exitAfterDefer
    godot:
      scope: all
    revive:
      severity: warning
      rules:
        - name: atomic
          disabled: false
        - name: blank-imports
          disabled: false
        - name: bool-literal-in-expr
          disabled: false
        - name: call-to-gc
          disabled: false
        - name: constant-logical-expr
          disabled: false
        - name: context-as-argument
          disabled: false
        - name: context-keys-type
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - return
          disabled: false
        - name: dot-imports
          disabled: false
        - name: duplicated-imports
          disabled: false
        - name: early-return
          disabled: false
        - name: empty-block
          disabled: false
        - name: error-naming
          disabled: false
        - name: error-return
          disabled: false
        - name: error-strings
          disabled: false
        - name: errorf
          disabled: false
        - name: exported
          disabled: false
        - name: get-return
          disabled: false
        - name: identical-branches
          disabled: false
        - name: increment-decrement
          disabled: false
        - name: indent-error-flow
          disabled: false
        - name: package-comments
          disabled: false
        - name: range
          disabled: false
        - name: range-val-in-closure
          disabled: false
        - name: range-val-address
          disabled: false
        - name: receiver-naming
          disabled: false
        - name: redefines-builtin-id
          disabled: false
        - name: string-of-int
          disabled: false
        - name: time-naming
          disabled: false
        - name: var-declaration
          disabled: false
        - name: var-naming
          disabled: false
        - name: unexported-naming
          disabled: false
        - name: unexported-return
          disabled: false
        - name: unnecessary-stmt
          disabled: false
        - name: unreachable-code
          disabled: false
        - name: unused-parameter
          disabled: false
        - name: useless-break
          disabled: false
    staticcheck:
      checks:
        - all
        - -SA9004
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: warning
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
      chain-split-dots: false
  exclusions:
    generated: lax
    paths:
      - tools$
